@startuml
'https://plantuml.com/sequence-diagram

title plantuml test
autonumber "<b>[0]"

skinparam BoxPadding 10
skinparam ParticipantPadding 50
skinparam SequenceBoxBorderColor tranparent

skinparam sequence {
	ArrowColor black
	LifeLineBorderColor black
	ParticipantBorderColor black
	ParticipantBackgroundColor lightskyblue  
	ActorBorderColor black      
	ActorBackgroundColor lightskyblue  
}

actor User as "User"



participant UserController as "userController"
'participant OrderController #red  

== main process ==
User -> UserController: login   
activate User #gold   

@enduml